In [1]:
import pandas as pd

In [2]:
path = 'Nizhnevartovsk_weather_2017-2022.csv'

df = pd.read_csv(path, sep=';')

In [3]:
df['Местное время в Нижневартовске / им. В. И. Муравленко (аэропорт)'] = pd.to_datetime(df['Местное время в Нижневартовске / им. В. И. Муравленко (аэропорт)'])

In [4]:
min_temp = df.groupby([df['Местное время в Нижневартовске / им. В. И. Муравленко (аэропорт)'].dt.date]).agg(min_temperature = pd.NamedAgg(column = 'Tn', aggfunc = 'min'))
min_temp.to_csv('Nizhnevartovsk_min_temperature.csv')

In [6]:
min_temp.head(25)

                                                    min_temperature
Местное время в Нижневартовске / им. В. И. Мура...
2017-12-17                                                     -9.8
2017-12-18                                                    -12.7
2017-12-19                                                     -9.1
2017-12-20                                                    -13.3
2017-12-21                                                    -10.5
2017-12-22                                                     -9.3
2017-12-23                                                     -8.0
2017-12-24                                                     -9.4
2017-12-25                                                    -15.0
2017-12-26                                                    -19.9
2017-12-27                                                    -24.4
2017-12-28                                                    -26.4
2017-12-29                                                    -19.6
2017-12-30                                                    -23.9
2017-12-31                                                    -27.0
2018-01-01                                                    -13.7
2018-01-02                                                    -20.2
2018-01-03                                                    -36.1
2018-01-04                                                    -25.4
2018-01-05                                                     -8.4
2018-01-06                                                  44751.0
2018-01-07                                                  44726.0
2018-01-08                                                  44809.0
2018-01-09                                                  44624.0
2018-01-10                                                  44656.0